// Generated by CoffeeScript 1.6.3
(function() {
  var XMLHttpRequest, app, db, express, mongoskin;

  express = require('express');

  mongoskin = require('mongoskin');

  db = mongoskin.db('mongodb://readuser:reader1234@SG-mssmongodev02-874.servers.mongodirector.com:27017/dev-test', {
    safe: false
  });

  XMLHttpRequest = require("xmlhttprequest").XMLHttpRequest;

  app = express();

  app.configure(function() {
    app.use(express.bodyParser());
    app.use(express["static"](__dirname));
    return app.use(express.favicon());
  });

  app.get('/titles', function(req, res) {
    /*
    # TODO: unable to find collection in the dev-test database
    
    # Using HTTP api in the meantime while there's no data in mongodb connection
    */

    var titles, xmlhttp;
    titles = '';
    xmlhttp = new XMLHttpRequest();
    xmlhttp.open('GET', 'http://dc.tbs.io/all', true);
    xmlhttp.onreadystatechange = function() {
      if (xmlhttp.readyState === 4 && xmlhttp.status === 200) {
        return res.end(xmlhttp.responseText);
      }
    };
    xmlhttp.send();
  });

  app.listen(3000);

}).call(this);
