// Generated by CoffeeScript 1.6.3
(function() {
  var app, db, express, mongoskin;

  express = require('express');

  mongoskin = require('mongoskin');

  db = mongoskin.db('mongodb://readuser:reader1234@SG-mssmongodev02-874.servers.mongodirector.com:27017/dev-test');

  app = express();

  app.configure(function() {
    app.use(express.bodyParser());
    app.use(express["static"](__dirname));
    return app.use(express.favicon());
  });

  app.get('/titles', function(req, res) {
    res.setHeader('Content-Type', 'text/json');
    return res.end(JSON.stringify({
      test: true
    }));
  });

  app.get('/titles/search', function(req, res) {
    res.setHeader('Content-Type', 'text/json');
    return res.end(JSON.stringify({
      test: true
    }));
  });

  app.listen(3000);

}).call(this);
